import type { Metadata } from 'next'
import Header from '@/components/header'
import Hero from '@/components/hero'
import CategoryNav from '@/components/category-nav'
import ProductCarousel from '@/components/product-carousel'
import Footer from '@/components/footer'

export const metadata: Metadata = {
  title: 'المتجر الرئيسي - TIX',
  description: 'متجر تسوق إلكتروني متكامل مع أفضل المنتجات والعروض',
  openGraph: {
    title: 'المتجر الرئيسي - TIX',
    description: 'متجر تسوق إلكتروني متكامل مع أفضل المنتجات والعروض',
    type: 'website',
    url: 'https://tix-eg.com',
  },
}

async function getProducts() {
  try {
    const res = await fetch('http://localhost:3000/api/products?limit=12', {
      cache: 'revalidate',
      next: { revalidate: 3600 }, // ISR: revalidate every hour
    })
    if (!res.ok) throw new Error('Failed to fetch products')
    const { data } = await res.json()
    return data
  } catch (error) {
    console.error('Error fetching products:', error)
    return []
  }
}

export default async function Home() {
  const newProducts = await getProducts()
  
  const fallbackProducts = [
    {
      id: 1,
      name: "سماعات لاسلكية بلوتوث",
      image: "/wireless-bluetooth-headphones.jpg",
      price: 299,
      originalPrice: 450,
      discount: 34,
      rating: 5,
    },
    {
      id: 2,
      name: "ساعة ذكية رياضية",
      image: "/smart-sports-watch.jpg",
      price: 899,
      originalPrice: 1200,
      discount: 25,
      rating: 4,
    },
    {
      id: 3,
      name: "شاحن لاسلكي سريع",
      image: "/fast-wireless-charger.jpg",
      price: 149,
      originalPrice: 220,
      discount: 32,
      rating: 5,
    },
    {
      id: 4,
      name: "كاميرا ويب عالية الدقة",
      image: "/hd-webcam.jpg",
      price: 399,
      originalPrice: 550,
      discount: 27,
      rating: 4,
    },
    {
      id: 5,
      name: "لوحة مفاتيح ميكانيكية",
      image: "/mechanical-keyboard-rgb.jpg",
      price: 599,
      originalPrice: 850,
      discount: 30,
      rating: 5,
    },
    {
      id: 6,
      name: "ماوس ألعاب احترافي",
      image: "/gaming-mouse-rgb.jpg",
      price: 249,
      originalPrice: 350,
      discount: 29,
      rating: 4,
    },
    {
      id: 7,
      name: "سماعة رأس للألعاب",
      image: "/gaming-headset.png",
      price: 449,
      originalPrice: 650,
      discount: 31,
      rating: 5,
    },
    {
      id: 8,
      name: "كابل شحن سريع USB-C",
      image: "/usb-c-fast-charging-cable.jpg",
      price: 79,
      originalPrice: 120,
      discount: 34,
      rating: 4,
    },
    {
      id: 9,
      name: "حامل هاتف للسيارة",
      image: "/car-phone-holder.jpg",
      price: 89,
      originalPrice: 140,
      discount: 36,
      rating: 5,
    },
    {
      id: 10,
      name: "بطارية محمولة 20000mAh",
      image: "/power-bank-20000mah.jpg",
      price: 299,
      originalPrice: 450,
      discount: 34,
      rating: 4,
    },

    // Fashion
    {
      id: 11,
      name: "قميص رجالي قطن",
      image: "/mens-cotton-shirt.jpg",
      price: 199,
      originalPrice: 300,
      discount: 34,
      rating: 4,
    },
    {
      id: 12,
      name: "فستان نسائي صيفي",
      image: "/womens-summer-dress.jpg",
      price: 349,
      originalPrice: 500,
      discount: 30,
      rating: 5,
    },
    {
      id: 13,
      name: "حذاء رياضي للجري",
      image: "/running-sports-shoes.jpg",
      price: 599,
      originalPrice: 850,
      discount: 30,
      rating: 5,
    },
    {
      id: 14,
      name: "حقيبة يد نسائية",
      image: "/womens-handbag.jpg",
      price: 449,
      originalPrice: 650,
      discount: 31,
      rating: 4,
    },
    {
      id: 15,
      name: "نظارة شمسية عصرية",
      image: "/trendy-sunglasses.jpg",
      price: 149,
      originalPrice: 220,
      discount: 32,
      rating: 4,
    },
    {
      id: 16,
      name: "ساعة يد رجالية",
      image: "/mens-wristwatch.jpg",
      price: 799,
      originalPrice: 1100,
      discount: 27,
      rating: 5,
    },
    {
      id: 17,
      name: "حزام جلد طبيعي",
      image: "/placeholder.svg?height=200&width=200",
      price: 179,
      originalPrice: 260,
      discount: 31,
      rating: 4,
    },
    {
      id: 18,
      name: "محفظة رجالية جلد",
      image: "/placeholder.svg?height=200&width=200",
      price: 199,
      originalPrice: 300,
      discount: 34,
      rating: 5,
    },
    {
      id: 19,
      name: "شال نسائي شتوي",
      image: "/placeholder.svg?height=200&width=200",
      price: 129,
      originalPrice: 190,
      discount: 32,
      rating: 4,
    },
    {
      id: 20,
      name: "قبعة رياضية",
      image: "/placeholder.svg?height=200&width=200",
      price: 99,
      originalPrice: 150,
      discount: 34,
      rating: 4,
    },

    // Home & Kitchen
    {
      id: 21,
      name: "خلاط كهربائي 5 سرعات",
      image: "/placeholder.svg?height=200&width=200",
      price: 399,
      originalPrice: 600,
      discount: 34,
      rating: 5,
    },
    {
      id: 22,
      name: "مقلاة هوائية 5 لتر",
      image: "/placeholder.svg?height=200&width=200",
      price: 899,
      originalPrice: 1300,
      discount: 31,
      rating: 5,
    },
    {
      id: 23,
      name: "طقم أواني طبخ",
      image: "/placeholder.svg?height=200&width=200",
      price: 699,
      originalPrice: 1000,
      discount: 30,
      rating: 4,
    },
    {
      id: 24,
      name: "غلاية كهربائية",
      image: "/placeholder.svg?height=200&width=200",
      price: 249,
      originalPrice: 370,
      discount: 33,
      rating: 5,
    },
    {
      id: 25,
      name: "محضرة طعام متعددة",
      image: "/placeholder.svg?height=200&width=200",
      price: 599,
      originalPrice: 850,
      discount: 30,
      rating: 4,
    },
    {
      id: 26,
      name: "مكواة بخار عمودية",
      image: "/placeholder.svg?height=200&width=200",
      price: 449,
      originalPrice: 650,
      discount: 31,
      rating: 5,
    },
    {
      id: 27,
      name: "مكنسة كهربائية",
      image: "/placeholder.svg?height=200&width=200",
      price: 799,
      originalPrice: 1150,
      discount: 31,
      rating: 4,
    },
    {
      id: 28,
      name: "طقم أكواب زجاج",
      image: "/placeholder.svg?height=200&width=200",
      price: 149,
      originalPrice: 220,
      discount: 32,
      rating: 4,
    },
    {
      id: 29,
      name: "طقم صحون سيراميك",
      image: "/placeholder.svg?height=200&width=200",
      price: 299,
      originalPrice: 450,
      discount: 34,
      rating: 5,
    },
    {
      id: 30,
      name: "سكاكين مطبخ احترافية",
      image: "/placeholder.svg?height=200&width=200",
      price: 349,
      originalPrice: 500,
      discount: 30,
      rating: 5,
    },

    // Books
    {
      id: 31,
      name: "كتاب تطوير الذات",
      image: "/placeholder.svg?height=200&width=200",
      price: 99,
      originalPrice: 150,
      discount: 34,
      rating: 5,
    },
    {
      id: 32,
      name: "رواية عربية",
      image: "/placeholder.svg?height=200&width=200",
      price: 79,
      originalPrice: 120,
      discount: 34,
      rating: 4,
    },
    {
      id: 33,
      name: "كتاب طبخ عالمي",
      image: "/placeholder.svg?height=200&width=200",
      price: 149,
      originalPrice: 220,
      discount: 32,
      rating: 5,
    },
    {
      id: 34,
      name: "كتاب تعليم البرمجة",
      image: "/placeholder.svg?height=200&width=200",
      price: 199,
      originalPrice: 300,
      discount: 34,
      rating: 5,
    },
    {
      id: 35,
      name: "قصص أطفال مصورة",
      image: "/placeholder.svg?height=200&width=200",
      price: 89,
      originalPrice: 140,
      discount: 36,
      rating: 4,
    },

    // Toys
    {
      id: 36,
      name: "سيارة تحكم عن بعد",
      image: "/placeholder.svg?height=200&width=200",
      price: 299,
      originalPrice: 450,
      discount: 34,
      rating: 5,
    },
    {
      id: 37,
      name: "مكعبات بناء للأطفال",
      image: "/placeholder.svg?height=200&width=200",
      price: 199,
      originalPrice: 300,
      discount: 34,
      rating: 4,
    },
    {
      id: 38,
      name: "دمية تفاعلية",
      image: "/placeholder.svg?height=200&width=200",
      price: 349,
      originalPrice: 500,
      discount: 30,
      rating: 5,
    },
    {
      id: 39,
      name: "لعبة ألغاز تعليمية",
      image: "/placeholder.svg?height=200&width=200",
      price: 149,
      originalPrice: 220,
      discount: 32,
      rating: 4,
    },
    {
      id: 40,
      name: "طائرة درون صغيرة",
      image: "/placeholder.svg?height=200&width=200",
      price: 599,
      originalPrice: 850,
      discount: 30,
      rating: 5,
    },

    // Sports
    {
      id: 41,
      name: "دراجة هوائية جبلية",
      image: "/placeholder.svg?height=200&width=200",
      price: 2499,
      originalPrice: 3500,
      discount: 29,
      rating: 5,
    },
    {
      id: 42,
      name: "حبل قفز رياضي",
      image: "/placeholder.svg?height=200&width=200",
      price: 79,
      originalPrice: 120,
      discount: 34,
      rating: 4,
    },
    {
      id: 43,
      name: "كرة قدم احترافية",
      image: "/placeholder.svg?height=200&width=200",
      price: 199,
      originalPrice: 300,
      discount: 34,
      rating: 5,
    },
    {
      id: 44,
      name: "حصيرة يوجا",
      image: "/placeholder.svg?height=200&width=200",
      price: 149,
      originalPrice: 220,
      discount: 32,
      rating: 4,
    },
    {
      id: 45,
      name: "أوزان رياضية قابلة للتعديل",
      image: "/placeholder.svg?height=200&width=200",
      price: 599,
      originalPrice: 850,
      discount: 30,
      rating: 5,
    },
    {
      id: 46,
      name: "حقيبة رياضية",
      image: "/placeholder.svg?height=200&width=200",
      price: 249,
      originalPrice: 370,
      discount: 33,
      rating: 4,
    },
    {
      id: 47,
      name: "زجاجة مياه رياضية",
      image: "/placeholder.svg?height=200&width=200",
      price: 89,
      originalPrice: 140,
      discount: 36,
      rating: 4,
    },
    {
      id: 48,
      name: "شريط مقاومة رياضي",
      image: "/placeholder.svg?height=200&width=200",
      price: 99,
      originalPrice: 150,
      discount: 34,
      rating: 5,
    },

    // Beauty
    {
      id: 49,
      name: "كريم ترطيب للوجه",
      image: "/placeholder.svg?height=200&width=200",
      price: 199,
      originalPrice: 300,
      discount: 34,
      rating: 5,
    },
    {
      id: 50,
      name: "شامبو للشعر الجاف",
      image: "/placeholder.svg?height=200&width=200",
      price: 149,
      originalPrice: 220,
      discount: 32,
      rating: 4,
    },
    {
      id: 51,
      name: "مجموعة مكياج",
      image: "/placeholder.svg?height=200&width=200",
      price: 499,
      originalPrice: 750,
      discount: 33,
      rating: 5,
    },
    {
      id: 52,
      name: "عطر نسائي فاخر",
      image: "/placeholder.svg?height=200&width=200",
      price: 799,
      originalPrice: 1150,
      discount: 31,
      rating: 5,
    },
    {
      id: 53,
      name: "فرشاة تنظيف الوجه",
      image: "/placeholder.svg?height=200&width=200",
      price: 249,
      originalPrice: 370,
      discount: 33,
      rating: 4,
    },
    {
      id: 54,
      name: "مجفف شعر احترافي",
      image: "/placeholder.svg?height=200&width=200",
      price: 599,
      originalPrice: 850,
      discount: 30,
      rating: 5,
    },

    // Baby & Kids
    {
      id: 55,
      name: "عربة أطفال قابلة للطي",
      image: "/placeholder.svg?height=200&width=200",
      price: 1499,
      originalPrice: 2200,
      discount: 32,
      rating: 5,
    },
    {
      id: 56,
      name: "كرسي سيارة للأطفال",
      image: "/placeholder.svg?height=200&width=200",
      price: 899,
      originalPrice: 1300,
      discount: 31,
      rating: 5,
    },
    {
      id: 57,
      name: "سرير أطفال خشبي",
      image: "/placeholder.svg?height=200&width=200",
      price: 1999,
      originalPrice: 2900,
      discount: 31,
      rating: 4,
    },
    {
      id: 58,
      name: "ملابس أطفال قطنية",
      image: "/placeholder.svg?height=200&width=200",
      price: 149,
      originalPrice: 220,
      discount: 32,
      rating: 4,
    },
    {
      id: 59,
      name: "زجاجة رضاعة",
      image: "/placeholder.svg?height=200&width=200",
      price: 79,
      originalPrice: 120,
      discount: 34,
      rating: 5,
    },

    // Furniture
    {
      id: 60,
      name: "كنبة ثلاثية مودرن",
      image: "/placeholder.svg?height=200&width=200",
      price: 4999,
      originalPrice: 7000,
      discount: 29,
      rating: 5,
    },
    {
      id: 61,
      name: "طاولة طعام خشبية",
      image: "/placeholder.svg?height=200&width=200",
      price: 2999,
      originalPrice: 4300,
      discount: 30,
      rating: 4,
    },
    {
      id: 62,
      name: "كرسي مكتب مريح",
      image: "/placeholder.svg?height=200&width=200",
      price: 1299,
      originalPrice: 1900,
      discount: 32,
      rating: 5,
    },
    {
      id: 63,
      name: "خزانة ملابس كبيرة",
      image: "/placeholder.svg?height=200&width=200",
      price: 3499,
      originalPrice: 5000,
      discount: 30,
      rating: 4,
    },
    {
      id: 64,
      name: "رف كتب خشبي",
      image: "/placeholder.svg?height=200&width=200",
      price: 899,
      originalPrice: 1300,
      discount: 31,
      rating: 4,
    },

    // Grocery
    {
      id: 65,
      name: "زيت زيتون بكر",
      image: "/placeholder.svg?height=200&width=200",
      price: 149,
      originalPrice: 220,
      discount: 32,
      rating: 5,
    },
    {
      id: 66,
      name: "عسل نحل طبيعي",
      image: "/placeholder.svg?height=200&width=200",
      price: 199,
      originalPrice: 300,
      discount: 34,
      rating: 5,
    },
    {
      id: 67,
      name: "أرز بسمتي",
      image: "/placeholder.svg?height=200&width=200",
      price: 89,
      originalPrice: 140,
      discount: 36,
      rating: 4,
    },
    {
      id: 68,
      name: "معكرونة إيطالية",
      image: "/placeholder.svg?height=200&width=200",
      price: 49,
      originalPrice: 80,
      discount: 39,
      rating: 4,
    },
    {
      id: 69,
      name: "قهوة عربية فاخرة",
      image: "/placeholder.svg?height=200&width=200",
      price: 129,
      originalPrice: 190,
      discount: 32,
      rating: 5,
    },

    // Automotive
    {
      id: 70,
      name: "مكنسة سيارة محمولة",
      image: "/placeholder.svg?height=200&width=200",
      price: 299,
      originalPrice: 450,
      discount: 34,
      rating: 4,
    },
    {
      id: 71,
      name: "كاميرا خلفية للسيارة",
      image: "/placeholder.svg?height=200&width=200",
      price: 399,
      originalPrice: 600,
      discount: 34,
      rating: 5,
    },
    {
      id: 72,
      name: "معطر سيارة فاخر",
      image: "/placeholder.svg?height=200&width=200",
      price: 79,
      originalPrice: 120,
      discount: 34,
      rating: 4,
    },
    {
      id: 73,
      name: "غطاء مقاعد سيارة",
      image: "/placeholder.svg?height=200&width=200",
      price: 349,
      originalPrice: 500,
      discount: 30,
      rating: 4,
    },
    {
      id: 74,
      name: "مضخة هواء للسيارة",
      image: "/placeholder.svg?height=200&width=200",
      price: 249,
      originalPrice: 370,
      discount: 33,
      rating: 5,
    },

    // Garden
    {
      id: 75,
      name: "خرطوم مياه قابل للتمدد",
      image: "/placeholder.svg?height=200&width=200",
      price: 199,
      originalPrice: 300,
      discount: 34,
      rating: 4,
    },
    {
      id: 76,
      name: "مقص تقليم الأشجار",
      image: "/placeholder.svg?height=200&width=200",
      price: 149,
      originalPrice: 220,
      discount: 32,
      rating: 5,
    },
    {
      id: 77,
      name: "أصيص نباتات ديكور",
      image: "/placeholder.svg?height=200&width=200",
      price: 99,
      originalPrice: 150,
      discount: 34,
      rating: 4,
    },
    {
      id: 78,
      name: "بذور خضروات متنوعة",
      image: "/placeholder.svg?height=200&width=200",
      price: 49,
      originalPrice: 80,
      discount: 39,
      rating: 4,
    },
    {
      id: 79,
      name: "سماد عضوي طبيعي",
      image: "/placeholder.svg?height=200&width=200",
      price: 129,
      originalPrice: 190,
      discount: 32,
      rating: 5,
    },

    // More Electronics
    {
      id: 80,
      name: "تابلت 10 بوصة",
      image: "/placeholder.svg?height=200&width=200",
      price: 1999,
      originalPrice: 2900,
      discount: 31,
      rating: 5,
    },
    {
      id: 81,
      name: "سماعات أذن لاسلكية",
      image: "/placeholder.svg?height=200&width=200",
      price: 399,
      originalPrice: 600,
      discount: 34,
      rating: 5,
    },
    {
      id: 82,
      name: "حامل لابتوب قابل للتعديل",
      image: "/placeholder.svg?height=200&width=200",
      price: 249,
      originalPrice: 370,
      discount: 33,
      rating: 4,
    },
    {
      id: 83,
      name: "مروحة USB صغيرة",
      image: "/placeholder.svg?height=200&width=200",
      price: 79,
      originalPrice: 120,
      discount: 34,
      rating: 4,
    },
    {
      id: 84,
      name: "إضاءة LED ذكية",
      image: "/placeholder.svg?height=200&width=200",
      price: 299,
      originalPrice: 450,
      discount: 34,
      rating: 5,
    },
    {
      id: 85,
      name: "مكبر صوت بلوتوث",
      image: "/placeholder.svg?height=200&width=200",
      price: 349,
      originalPrice: 500,
      discount: 30,
      rating: 4,
    },

    // More Fashion
    {
      id: 86,
      name: "جاكيت جينز رجالي",
      image: "/placeholder.svg?height=200&width=200",
      price: 449,
      originalPrice: 650,
      discount: 31,
      rating: 5,
    },
    {
      id: 87,
      name: "بنطلون رياضي نسائي",
      image: "/placeholder.svg?height=200&width=200",
      price: 249,
      originalPrice: 370,
      discount: 33,
      rating: 4,
    },
    {
      id: 88,
      name: "حذاء كاجوال رجالي",
      image: "/placeholder.svg?height=200&width=200",
      price: 499,
      originalPrice: 750,
      discount: 33,
      rating: 5,
    },
    {
      id: 89,
      name: "شنطة ظهر عصرية",
      image: "/placeholder.svg?height=200&width=200",
      price: 299,
      originalPrice: 450,
      discount: 34,
      rating: 4,
    },
    {
      id: 90,
      name: "قفازات شتوية",
      image: "/placeholder.svg?height=200&width=200",
      price: 99,
      originalPrice: 150,
      discount: 34,
      rating: 4,
    },

    // More Home Items
    {
      id: 91,
      name: "مصباح أرضي مودرن",
      image: "/placeholder.svg?height=200&width=200",
      price: 599,
      originalPrice: 850,
      discount: 30,
      rating: 5,
    },
    {
      id: 92,
      name: "سجادة غرفة معيشة",
      image: "/placeholder.svg?height=200&width=200",
      price: 799,
      originalPrice: 1150,
      discount: 31,
      rating: 4,
    },
    {
      id: 93,
      name: "ستائر تعتيم كاملة",
      image: "/placeholder.svg?height=200&width=200",
      price: 349,
      originalPrice: 500,
      discount: 30,
      rating: 4,
    },
    {
      id: 94,
      name: "مرآة حائط ديكور",
      image: "/placeholder.svg?height=200&width=200",
      price: 449,
      originalPrice: 650,
      discount: 31,
      rating: 5,
    },
    {
      id: 95,
      name: "وسائد كنب ملونة",
      image: "/placeholder.svg?height=200&width=200",
      price: 149,
      originalPrice: 220,
      discount: 32,
      rating: 4,
    },

    // Final Items
    {
      id: 96,
      name: "ميزان حرارة رقمي",
      image: "/placeholder.svg?height=200&width=200",
      price: 99,
      originalPrice: 150,
      discount: 34,
      rating: 5,
    },
    {
      id: 97,
      name: "جهاز قياس ضغط الدم",
      image: "/placeholder.svg?height=200&width=200",
      price: 399,
      originalPrice: 600,
      discount: 34,
      rating: 5,
    },
    {
      id: 98,
      name: "حقيبة سفر كبيرة",
      image: "/placeholder.svg?height=200&width=200",
      price: 899,
      originalPrice: 1300,
      discount: 31,
      rating: 4,
    },
    {
      id: 99,
      name: "مظلة أوتوماتيكية",
      image: "/placeholder.svg?height=200&width=200",
      price: 129,
      originalPrice: 190,
      discount: 32,
      rating: 4,
    },
    {
      id: 100,
      name: "ساعة حائط ديكور",
      image: "/placeholder.svg?height=200&width=200",
      price: 199,
      originalPrice: 300,
      discount: 34,
      rating: 5,
    },
  ]

  const offerProducts = [
    // High discount electronics
    {
      id: 101,
      name: "لابتوب جيمنج",
      image: "/placeholder.svg?height=200&width=200",
      price: 8999,
      originalPrice: 15000,
      discount: 40,
      rating: 5,
    },
    {
      id: 102,
      name: "شاشة 4K 55 بوصة",
      image: "/placeholder.svg?height=200&width=200",
      price: 5999,
      originalPrice: 10000,
      discount: 40,
      rating: 5,
    },
    {
      id: 103,
      name: "هاتف ذكي 5G",
      image: "/placeholder.svg?height=200&width=200",
      price: 4499,
      originalPrice: 7500,
      discount: 40,
      rating: 5,
    },
    {
      id: 104,
      name: "كاميرا رقمية احترافية",
      image: "/placeholder.svg?height=200&width=200",
      price: 6999,
      originalPrice: 11000,
      discount: 36,
      rating: 5,
    },
    {
      id: 105,
      name: "طابعة ليزر ملونة",
      image: "/placeholder.svg?height=200&width=200",
      price: 2499,
      originalPrice: 4000,
      discount: 38,
      rating: 4,
    },
    {
      id: 106,
      name: "راوتر واي فاي 6",
      image: "/placeholder.svg?height=200&width=200",
      price: 899,
      originalPrice: 1500,
      discount: 40,
      rating: 5,
    },
    {
      id: 107,
      name: "قرص صلب خارجي 2TB",
      image: "/placeholder.svg?height=200&width=200",
      price: 599,
      originalPrice: 1000,
      discount: 40,
      rating: 4,
    },
    {
      id: 108,
      name: "ذاكرة فلاش 128GB",
      image: "/placeholder.svg?height=200&width=200",
      price: 149,
      originalPrice: 250,
      discount: 40,
      rating: 4,
    },
    {
      id: 109,
      name: "سماعات استوديو",
      image: "/placeholder.svg?height=200&width=200",
      price: 1199,
      originalPrice: 2000,
      discount: 40,
      rating: 5,
    },
    {
      id: 110,
      name: "ميكروفون احترافي",
      image: "/placeholder.svg?height=200&width=200",
      price: 899,
      originalPrice: 1500,
      discount: 40,
      rating: 5,
    },

    // Fashion deals
    {
      id: 111,
      name: "معطف شتوي فاخر",
      image: "/placeholder.svg?height=200&width=200",
      price: 999,
      originalPrice: 1800,
      discount: 44,
      rating: 5,
    },
    {
      id: 112,
      name: "بدلة رجالية رسمية",
      image: "/placeholder.svg?height=200&width=200",
      price: 1499,
      originalPrice: 2500,
      discount: 40,
      rating: 5,
    },
    {
      id: 113,
      name: "فستان سهرة نسائي",
      image: "/placeholder.svg?height=200&width=200",
      price: 799,
      originalPrice: 1400,
      discount: 43,
      rating: 5,
    },
    {
      id: 114,
      name: "حذاء كعب عالي",
      image: "/placeholder.svg?height=200&width=200",
      price: 449,
      originalPrice: 750,
      discount: 40,
      rating: 4,
    },
    {
      id: 115,
      name: "حقيبة سفر جلد",
      image: "/placeholder.svg?height=200&width=200",
      price: 899,
      originalPrice: 1500,
      discount: 40,
      rating: 5,
    },
    {
      id: 116,
      name: "ربطة عنق حريرية",
      image: "/placeholder.svg?height=200&width=200",
      price: 149,
      originalPrice: 250,
      discount: 40,
      rating: 4,
    },
    {
      id: 117,
      name: "عباية نسائية مطرزة",
      image: "/placeholder.svg?height=200&width=200",
      price: 599,
      originalPrice: 1000,
      discount: 40,
      rating: 5,
    },
    {
      id: 118,
      name: "حذاء رياضي ماركة",
      image: "/placeholder.svg?height=200&width=200",
      price: 899,
      originalPrice: 1500,
      discount: 40,
      rating: 5,
    },

    // Home appliances
    {
      id: 119,
      name: "ثلاجة نوفروست كبيرة",
      image: "/placeholder.svg?height=200&width=200",
      price: 7999,
      originalPrice: 13000,
      discount: 38,
      rating: 5,
    },
    {
      id: 120,
      name: "غسالة أوتوماتيك 10 كيلو",
      image: "/placeholder.svg?height=200&width=200",
      price: 4999,
      originalPrice: 8000,
      discount: 38,
      rating: 5,
    },
    {
      id: 121,
      name: "مكيف هواء 2.25 حصان",
      image: "/placeholder.svg?height=200&width=200",
      price: 5499,
      originalPrice: 9000,
      discount: 39,
      rating: 5,
    },
    {
      id: 122,
      name: "فرن كهربائي كبير",
      image: "/placeholder.svg?height=200&width=200",
      price: 2999,
      originalPrice: 5000,
      discount: 40,
      rating: 4,
    },
    {
      id: 123,
      name: "ميكروويف ديجيتال",
      image: "/placeholder.svg?height=200&width=200",
      price: 1499,
      originalPrice: 2500,
      discount: 40,
      rating: 4,
    },
    {
      id: 124,
      name: "مروحة سقف حديثة",
      image: "/placeholder.svg?height=200&width=200",
      price: 899,
      originalPrice: 1500,
      discount: 40,
      rating: 4,
    },
    {
      id: 125,
      name: "سخان مياه كهربائي",
      image: "/placeholder.svg?height=200&width=200",
      price: 1999,
      originalPrice: 3300,
      discount: 39,
      rating: 5,
    },

    // Kitchen items
    {
      id: 126,
      name: "ماكينة قهوة اسبريسو",
      image: "/placeholder.svg?height=200&width=200",
      price: 2499,
      originalPrice: 4200,
      discount: 40,
      rating: 5,
    },
    {
      id: 127,
      name: "عصارة فواكه كهربائية",
      image: "/placeholder.svg?height=200&width=200",
      price: 599,
      originalPrice: 1000,
      discount: 40,
      rating: 4,
    },
    {
      id: 128,
      name: "طنجرة ضغط كهربائية",
      image: "/placeholder.svg?height=200&width=200",
      price: 899,
      originalPrice: 1500,
      discount: 40,
      rating: 5,
    },
    {
      id: 129,
      name: "محمصة خبز 4 شرائح",
      image: "/placeholder.svg?height=200&width=200",
      price: 449,
      originalPrice: 750,
      discount: 40,
      rating: 4,
    },
    {
      id: 130,
      name: "ميزان مطبخ رقمي",
      image: "/placeholder.svg?height=200&width=200",
      price: 179,
      originalPrice: 300,
      discount: 40,
      rating: 4,
    },

    // Sports equipment
    {
      id: 131,
      name: "جهاز مشي كهربائي",
      image: "/placeholder.svg?height=200&width=200",
      price: 5999,
      originalPrice: 10000,
      discount: 40,
      rating: 5,
    },
    {
      id: 132,
      name: "دراجة تمارين منزلية",
      image: "/placeholder.svg?height=200&width=200",
      price: 2999,
      originalPrice: 5000,
      discount: 40,
      rating: 5,
    },
    {
      id: 133,
      name: "جهاز تمارين متعدد",
      image: "/placeholder.svg?height=200&width=200",
      price: 7999,
      originalPrice: 13000,
      discount: 38,
      rating: 5,
    },
    {
      id: 134,
      name: "طقم أوزان كامل",
      image: "/placeholder.svg?height=200&width=200",
      price: 1499,
      originalPrice: 2500,
      discount: 40,
      rating: 4,
    },
    {
      id: 135,
      name: "كرة سلة احترافية",
      image: "/placeholder.svg?height=200&width=200",
      price: 299,
      originalPrice: 500,
      discount: 40,
      rating: 5,
    },
    {
      id: 136,
      name: "مضرب تنس مع كرات",
      image: "/placeholder.svg?height=200&width=200",
      price: 599,
      originalPrice: 1000,
      discount: 40,
      rating: 4,
    },

    // Beauty products
    {
      id: 137,
      name: "مجموعة عناية بالبشرة",
      image: "/placeholder.svg?height=200&width=200",
      price: 899,
      originalPrice: 1500,
      discount: 40,
      rating: 5,
    },
    {
      id: 138,
      name: "مكواة شعر سيراميك",
      image: "/placeholder.svg?height=200&width=200",
      price: 449,
      originalPrice: 750,
      discount: 40,
      rating: 5,
    },
    {
      id: 139,
      name: "جهاز ليزر منزلي",
      image: "/placeholder.svg?height=200&width=200",
      price: 1999,
      originalPrice: 3300,
      discount: 39,
      rating: 5,
    },
    {
      id: 140,
      name: "عطر رجالي فاخر",
      image: "/placeholder.svg?height=200&width=200",
      price: 599,
      originalPrice: 1000,
      discount: 40,
      rating: 5,
    },
    {
      id: 141,
      name: "مجموعة مكياج كاملة",
      image: "/placeholder.svg?height=200&width=200",
      price: 1199,
      originalPrice: 2000,
      discount: 40,
      rating: 5,
    },

    // Baby products
    {
      id: 142,
      name: "سرير أطفال متحرك",
      image: "/placeholder.svg?height=200&width=200",
      price: 2999,
      originalPrice: 5000,
      discount: 40,
      rating: 5,
    },
    {
      id: 143,
      name: "كرسي طعام للأطفال",
      image: "/placeholder.svg?height=200&width=200",
      price: 899,
      originalPrice: 1500,
      discount: 40,
      rating: 4,
    },
    {
      id: 144,
      name: "مراقب أطفال بالفيديو",
      image: "/placeholder.svg?height=200&width=200",
      price: 1199,
      originalPrice: 2000,
      discount: 40,
      rating: 5,
    },
    {
      id: 145,
      name: "حقيبة حفاضات عملية",
      image: "/placeholder.svg?height=200&width=200",
      price: 299,
      originalPrice: 500,
      discount: 40,
      rating: 4,
    },
    {
      id: 146,
      name: "لعبة تعليمية للرضع",
      image: "/placeholder.svg?height=200&width=200",
      price: 449,
      originalPrice: 750,
      discount: 40,
      rating: 5,
    },

    // Furniture deals
    {
      id: 147,
      name: "غرفة نوم كاملة",
      image: "/placeholder.svg?height=200&width=200",
      price: 11999,
      originalPrice: 20000,
      discount: 40,
      rating: 5,
    },
    {
      id: 148,
      name: "طقم صالون مودرن",
      image: "/placeholder.svg?height=200&width=200",
      price: 8999,
      originalPrice: 15000,
      discount: 40,
      rating: 5,
    },
    {
      id: 149,
      name: "مكتب دراسة خشبي",
      image: "/placeholder.svg?height=200&width=200",
      price: 1499,
      originalPrice: 2500,
      discount: 40,
      rating: 4,
    },
    {
      id: 150,
      name: "كرسي استرخاء جلد",
      image: "/placeholder.svg?height=200&width=200",
      price: 2999,
      originalPrice: 5000,
      discount: 40,
      rating: 5,
    },
    {
      id: 151,
      name: "طاولة قهوة زجاجية",
      image: "/placeholder.svg?height=200&width=200",
      price: 899,
      originalPrice: 1500,
      discount: 40,
      rating: 4,
    },

    // Toys on sale
    {
      id: 152,
      name: "مجموعة ليجو كبيرة",
      image: "/placeholder.svg?height=200&width=200",
      price: 899,
      originalPrice: 1500,
      discount: 40,
      rating: 5,
    },
    {
      id: 153,
      name: "دراجة أطفال بعجلات",
      image: "/placeholder.svg?height=200&width=200",
      price: 599,
      originalPrice: 1000,
      discount: 40,
      rating: 4,
    },
    {
      id: 154,
      name: "بيت لعب للأطفال",
      image: "/placeholder.svg?height=200&width=200",
      price: 1499,
      originalPrice: 2500,
      discount: 40,
      rating: 5,
    },
    {
      id: 155,
      name: "سكوتر كهربائي للأطفال",
      image: "/placeholder.svg?height=200&width=200",
      price: 1799,
      originalPrice: 3000,
      discount: 40,
      rating: 5,
    },
    {
      id: 156,
      name: "مجموعة ألعاب تعليمية",
      image: "/placeholder.svg?height=200&width=200",
      price: 449,
      originalPrice: 750,
      discount: 40,
      rating: 4,
    },

    // Books on sale
    {
      id: 157,
      name: "موسوعة علمية للأطفال",
      image: "/placeholder.svg?height=200&width=200",
      price: 299,
      originalPrice: 500,
      discount: 40,
      rating: 5,
    },
    {
      id: 158,
      name: "مجموعة روايات عالمية",
      image: "/placeholder.svg?height=200&width=200",
      price: 449,
      originalPrice: 750,
      discount: 40,
      rating: 5,
    },
    {
      id: 159,
      name: "كتاب تعليم اللغات",
      image: "/placeholder.svg?height=200&width=200",
      price: 179,
      originalPrice: 300,
      discount: 40,
      rating: 4,
    },
    {
      id: 160,
      name: "قاموس عربي إنجليزي",
      image: "/placeholder.svg?height=200&width=200",
      price: 149,
      originalPrice: 250,
      discount: 40,
      rating: 4,
    },

    // Automotive deals
    {
      id: 161,
      name: "جهاز تتبع GPS للسيارة",
      image: "/placeholder.svg?height=200&width=200",
      price: 599,
      originalPrice: 1000,
      discount: 40,
      rating: 5,
    },
    {
      id: 162,
      name: "مسجل فيديو للسيارة",
      image: "/placeholder.svg?height=200&width=200",
      price: 899,
      originalPrice: 1500,
      discount: 40,
      rating: 5,
    },
    {
      id: 163,
      name: "مشغل موسيقى للسيارة",
      image: "/placeholder.svg?height=200&width=200",
      price: 1199,
      originalPrice: 2000,
      discount: 40,
      rating: 4,
    },
    {
      id: 164,
      name: "إطارات سيارة مجموعة",
      image: "/placeholder.svg?height=200&width=200",
      price: 2999,
      originalPrice: 5000,
      discount: 40,
      rating: 5,
    },
    {
      id: 165,
      name: "بطارية سيارة قوية",
      image: "/placeholder.svg?height=200&width=200",
      price: 899,
      originalPrice: 1500,
      discount: 40,
      rating: 5,
    },

    // Garden equipment
    {
      id: 166,
      name: "جزازة عشب كهربائية",
      image: "/placeholder.svg?height=200&width=200",
      price: 2499,
      originalPrice: 4200,
      discount: 40,
      rating: 5,
    },
    {
      id: 167,
      name: "مجموعة أدوات حديقة",
      image: "/placeholder.svg?height=200&width=200",
      price: 599,
      originalPrice: 1000,
      discount: 40,
      rating: 4,
    },
    {
      id: 168,
      name: "نافورة حديقة ديكور",
      image: "/placeholder.svg?height=200&width=200",
      price: 1499,
      originalPrice: 2500,
      discount: 40,
      rating: 5,
    },
    {
      id: 169,
      name: "طقم أثاث حديقة",
      image: "/placeholder.svg?height=200&width=200",
      price: 3999,
      originalPrice: 6700,
      discount: 40,
      rating: 5,
    },
    {
      id: 170,
      name: "مظلة حديقة كبيرة",
      image: "/placeholder.svg?height=200&width=200",
      price: 899,
      originalPrice: 1500,
      discount: 40,
      rating: 4,
    },

    // More electronics deals
    {
      id: 171,
      name: "بروجكتر منزلي HD",
      image: "/placeholder.svg?height=200&width=200",
      price: 2999,
      originalPrice: 5000,
      discount: 40,
      rating: 5,
    },
    {
      id: 172,
      name: "ساوند بار للتلفزيون",
      image: "/placeholder.svg?height=200&width=200",
      price: 1499,
      originalPrice: 2500,
      discount: 40,
      rating: 5,
    },
    {
      id: 173,
      name: "كونسول ألعاب",
      image: "/placeholder.svg?height=200&width=200",
      price: 5999,
      originalPrice: 10000,
      discount: 40,
      rating: 5,
    },
    {
      id: 174,
      name: "سماعة واقع افتراضي",
      image: "/placeholder.svg?height=200&width=200",
      price: 2499,
      originalPrice: 4200,
      discount: 40,
      rating: 5,
    },
    {
      id: 175,
      name: "ماسح ضوئي مستندات",
      image: "/placeholder.svg?height=200&width=200",
      price: 899,
      originalPrice: 1500,
      discount: 40,
      rating: 4,
    },

    // Office supplies
    {
      id: 176,
      name: "آلة تقطيع ورق",
      image: "/placeholder.svg?height=200&width=200",
      price: 599,
      originalPrice: 1000,
      discount: 40,
      rating: 4,
    },
    {
      id: 177,
      name: "لوح كتابة ذكي",
      image: "/placeholder.svg?height=200&width=200",
      price: 1199,
      originalPrice: 2000,
      discount: 40,
      rating: 5,
    },
    {
      id: 178,
      name: "مكتب قابل للتعديل",
      image: "/placeholder.svg?height=200&width=200",
      price: 2999,
      originalPrice: 5000,
      discount: 40,
      rating: 5,
    },
    {
      id: 179,
      name: "خزانة ملفات معدنية",
      image: "/placeholder.svg?height=200&width=200",
      price: 1499,
      originalPrice: 2500,
      discount: 40,
      rating: 4,
    },
    {
      id: 180,
      name: "مصباح مكتب LED",
      image: "/placeholder.svg?height=200&width=200",
      price: 299,
      originalPrice: 500,
      discount: 40,
      rating: 4,
    },

    // Health & wellness
    {
      id: 181,
      name: "جهاز مساج كهربائي",
      image: "/placeholder.svg?height=200&width=200",
      price: 899,
      originalPrice: 1500,
      discount: 40,
      rating: 5,
    },
    {
      id: 182,
      name: "ميزان ذكي للجسم",
      image: "/placeholder.svg?height=200&width=200",
      price: 449,
      originalPrice: 750,
      discount: 40,
      rating: 5,
    },
    {
      id: 183,
      name: "جهاز تنقية هواء",
      image: "/placeholder.svg?height=200&width=200",
      price: 1499,
      originalPrice: 2500,
      discount: 40,
      rating: 5,
    },
    {
      id: 184,
      name: "مرطب هواء بالبخار",
      image: "/placeholder.svg?height=200&width=200",
      price: 599,
      originalPrice: 1000,
      discount: 40,
      rating: 4,
    },
    {
      id: 185,
      name: "جهاز قياس السكر",
      image: "/placeholder.svg?height=200&width=200",
      price: 299,
      originalPrice: 500,
      discount: 40,
      rating: 5,
    },

    // Pet supplies
    {
      id: 186,
      name: "بيت قطط فاخر",
      image: "/placeholder.svg?height=200&width=200",
      price: 599,
      originalPrice: 1000,
      discount: 40,
      rating: 4,
    },
    {
      id: 187,
      name: "طعام كلاب ممتاز",
      image: "/placeholder.svg?height=200&width=200",
      price: 299,
      originalPrice: 500,
      discount: 40,
      rating: 5,
    },
    {
      id: 188,
      name: "قفص طيور كبير",
      image: "/placeholder.svg?height=200&width=200",
      price: 899,
      originalPrice: 1500,
      discount: 40,
      rating: 4,
    },
    {
      id: 189,
      name: "حوض سمك مع فلتر",
      image: "/placeholder.svg?height=200&width=200",
      price: 1199,
      originalPrice: 2000,
      discount: 40,
      rating: 5,
    },
    {
      id: 190,
      name: "لعبة تفاعلية للحيوانات",
      image: "/placeholder.svg?height=200&width=200",
      price: 179,
      originalPrice: 300,
      discount: 40,
      rating: 4,
    },

    // Musical instruments
    {
      id: 191,
      name: "جيتار كلاسيكي",
      image: "/placeholder.svg?height=200&width=200",
      price: 1499,
      originalPrice: 2500,
      discount: 40,
      rating: 5,
    },
    {
      id: 192,
      name: "كيبورد موسيقي",
      image: "/placeholder.svg?height=200&width=200",
      price: 2999,
      originalPrice: 5000,
      discount: 40,
      rating: 5,
    },
    {
      id: 193,
      name: "طبلة إلكترونية",
      image: "/placeholder.svg?height=200&width=200",
      price: 3999,
      originalPrice: 6700,
      discount: 40,
      rating: 5,
    },
    {
      id: 194,
      name: "عود شرقي",
      image: "/placeholder.svg?height=200&width=200",
      price: 1799,
      originalPrice: 3000,
      discount: 40,
      rating: 5,
    },

    // Camping & outdoor
    {
      id: 195,
      name: "خيمة تخييم عائلية",
      image: "/placeholder.svg?height=200&width=200",
      price: 1499,
      originalPrice: 2500,
      discount: 40,
      rating: 5,
    },
    {
      id: 196,
      name: "كيس نوم شتوي",
      image: "/placeholder.svg?height=200&width=200",
      price: 599,
      originalPrice: 1000,
      discount: 40,
      rating: 4,
    },
    {
      id: 197,
      name: "شواية فحم محمولة",
      image: "/placeholder.svg?height=200&width=200",
      price: 899,
      originalPrice: 1500,
      discount: 40,
      rating: 5,
    },
    {
      id: 198,
      name: "كشاف LED قوي",
      image: "/placeholder.svg?height=200&width=200",
      price: 299,
      originalPrice: 500,
      discount: 40,
      rating: 4,
    },
    {
      id: 199,
      name: "حقيبة ظهر للتخييم",
      image: "/placeholder.svg?height=200&width=200",
      price: 799,
      originalPrice: 1350,
      discount: 41,
      rating: 5,
    },
    {
      id: 200,
      name: "بوصلة ملاحية احترافية",
      image: "/placeholder.svg?height=200&width=200",
      price: 179,
      originalPrice: 300,
      discount: 40,
      rating: 4,
    },
  ]

  const productsToDisplay = newProducts && newProducts.length > 0 ? newProducts : fallbackProducts

  return (
    <div className="flex flex-col min-h-screen bg-white" dir="rtl">
      <Header />
      <Hero />
      <CategoryNav />
      <ProductCarousel title="منتجات جديدة" products={productsToDisplay} />
      <Footer />
    </div>
  )
}
